export const FETCH_FUNCTION_CATEGORIES_REQUESTED = "FETCH_FUNCTION_CATEGORIES_REQUESTED";
export const FETCH_FUNCTION_CATEGORIES_SUCCEEDED = "FETCH_FUNCTION_CATEGORIES_SUCCEEDED";
export const FETCH_FUNCTION_CATEGORIES_FAILED = "FETCH_FUNCTION_CATEGORIES_FAILED";

export const FETCH_FUNCTIONS_REQUESTED = "FETCH_FUNCTIONS_REQUESTED";
export const FETCH_FUNCTIONS_SUCCEEDED = "FETCH_FUNCTIONS_SUCCEEDED";
export const FETCH_FUNCTIONS_FAILED = "FETCH_FUNCTIONS_FAILED";

export const FETCH_FUNCTION_SUGGESTIONS_REQUESTED = "FETCH_FUNCTION_SUGGESTIONS_REQUESTED";
export const FETCH_FUNCTION_SUGGESTIONS_SUCCEEDED = "FETCH_FUNCTION_SUGGESTIONS_SUCCEEDED";
export const FETCH_FUNCTION_SUGGESTIONS_FAILED = "FETCH_FUNCTION_SUGGESTIONS_FAILED";

export const FETCH_FUNCTION_DESCRIPTION_REQUESTED = "FETCH_FUNCTION_DESCRIPTION_REQUESTED";
export const FETCH_FUNCTION_DESCRIPTION_SUCCEEDED = "FETCH_FUNCTION_DESCRIPTION_SUCCEEDED";
export const FETCH_FUNCTION_DESCRIPTION_FAILED = "FETCH_FUNCTION_DESCRIPTION_FAILED";

export const FETCH_FUNCTION_PARAMETERS_REQUESTED = "FETCH_FUNCTION_PARAMETERS_REQUESTED";
export const FETCH_FUNCTION_PARAMETERS_SUCCEEDED = "FETCH_FUNCTION_PARAMETERS_SUCCEEDED";
export const FETCH_FUNCTION_PARAMETERS_FAILED = "FETCH_FUNCTION_PARAMETERS_FAILED";


export const SET_COLUMN_SELECTION = "SET_COLUMN_SELECTION";

export const SET_CURRENT_FUNCTION = "SET_CURRENT_FUNCTION";
export const UNSET_CURRENT_FUNCTION = "UNSET_CURRENT_FUNCTION";

export const SET_PARAMETER_FLYOUT = "SET_PARAMETER_FLYOUT";
export const UNSET_PARAMETER_FLYOUT = "UNSET_PARAMETER_FLYOUT";

export const SET_CURRENT_FUNCTION_CATEGORY = "SET_CURRENT_FUNCTION_CATEGORY";
export const UNSET_CURRENT_FUNCTION_CATEGORY = "UNSET_CURRENT_FUNCTION_CATEGORY";

export const SET_FUNCTION_PARAMETERS = "SET_FUNCTION_PARAMETERS";
export const UNSET_FUNCTION_PARAMETERS = "UNSET_FUNCTION_PARAMETERS";