export const FETCH_FUNCTION_CATEGORIES_REQUESTED = "FETCH_FUNCTION_CATEGORIES_REQUESTED";
export const FETCH_FUNCTION_CATEGORIES_SUCCEEDED = "FETCH_FUNCTION_CATEGORIES_SUCCEEDED";
export const FETCH_FUNCTION_CATEGORIES_FAILED = "FETCH_FUNCTION_CATEGORIES_FAILED";


export const FETCH_FUNCTIONS_REQUESTED = "FETCH_FUNCTIONS_REQUESTED";
export const FETCH_FUNCTIONS_SUCCEEDED = "FETCH_FUNCTIONS_SUCCEEDED";
export const FETCH_FUNCTIONS_FAILED = "FETCH_FUNCTIONS_FAILED";