export const FETCH_CASE_REQUESTED = "FETCH_CASE_REQUESTED";
export const FETCH_CASE_SUCCEEDED = "FETCH_CASE_SUCCEEDED";
export const FETCH_CASE_FAILED = "FETCH_CASE_FAILED";

export const FETCH_STEPS_REQUESTED = "FETCH_STEPS_REQUESTED";
export const FETCH_STEPS_SUCCEEDED = "FETCH_STEPS_SUCCEEDED";
export const FETCH_STEPS_FAILED = "FETCH_STEPS_FAILED";


export const ADD_DATASETS = "ADD_DATASETS";

export const FETCH_RESULTS_ERR0R_REQUESTED = "FETCH_RESULTS_ERROR_REQUESTED";
export const FETCH_RESULTS_ERROR_SUCCEEDED = "FETCH_RESULTS_ERROR_SUCCEEDED";
export const FETCH_RESULTS_ERROR_FAILED = "FETCH_RESULTS_ERROR_FAILED";


export const SET_CURRENT_STEP = "SET_CURRENT_STEP"
export const SET_PREVIOUS_STEP = "SET_PREVIOUS_STEP"

export const OPEN_FLYOUT_PRIMARY = "OPEN_FLYOUT_PRIMARY"
export const CLOSE_FLYOUT_PRIMARY = "CLOSE_FLYOUT_PRIMARY"

export const OPEN_FLYOUT_SECONDARY = "OPEN_FLYOUT_SECONDARY"
export const CLOSE_FLYOUT_SECONDARY = "CLOSE_FLYOUT_SECONDARY"


export const UNDO_REQUESTED= "UNDO_REQUESTED"
export const UNDO_SUCCEEDED = "UNDO_SUCCEEDED"
export const UNDO_FAILED = "UNDO_FAILED"

export const REDO_REQUESTED= "REDO_REQUESTED"
export const REDO_SUCCEEDED = "REDO_SUCCEEDED"
export const REDO_FAILED = "REDO_FAILED"

