export const FETCH_CASE_REQUESTED = "FETCH_CASE_REQUESTED";
export const FETCH_CASE_SUCCEEDED = "FETCH_CASE_SUCCEEDED";
export const FETCH_CASE_FAILED = "FETCH_CASE_FAILED";

export const FETCH_STEPS_REQUESTED = "FETCH_STEPS_REQUESTED";
export const FETCH_STEPS_SUCCEEDED = "FETCH_STEPS_SUCCEEDED";
export const FETCH_STEPS_FAILED = "FETCH_STEPS_FAILED";
