export const FETCH_NOTES_REQUESTED = "FETCH_NOTES_REQUESTED";
export const FETCH_NOTES_SUCCEEDED = "FETCH_NOTES_SUCCEEDED";
export const FETCH_NOTES_FAILED = "FETCH_NOTES_FAILED";

export const CLOSE_NOTES_FLYOUT = 'CLOSE_NOTES_FLYOUT';

export const SAVE_CURRENT_STEP = 'SAVE_CURRENT_STEP';