export const FETCH_NOTES_REQUESTED = "FETCH_NOTES_REQUESTED";
export const FETCH_NOTES_SUCCEEDED = "FETCH_NOTES_SUCCEEDED";
export const FETCH_NOTES_FAILED = "FETCH_NOTES_FAILED";

export const CLOSE_NOTES_FLYOUT = 'CLOSE_NOTES_FLYOUT';

export const SAVE_CURRENT_STEP = 'SAVE_CURRENT_STEP';


export const SET_CURRENT_NOTES = "SET_CURRENT_NOTES";
export const SET_PREVIOUS_NOTES = "SET_PREVIOUS_NOTES";

export const OPEN_FLYOUT_PRIMARY = "OPEN_FLYOUT_PRIMARY";
export const CLOSE_FLYOUT_PRIMARY = "CLOSE_FLYOUT_PRIMARY";

export const OPEN_FLYOUT_SECONDARY = "OPEN_FLYOUT_SECONDARY";
export const CLOSE_FLYOUT_SECONDARY = "CLOSE_FLYOUT_SECONDARY";


export const SAVE_NOTES_REQUESTED = "SAVE_NOTES_REQUESTED";
export const SAVE_NOTES_SUCCEEDED = "SAVE_NOTES_SUCCEEDED";
export const SAVE_NOTES_FAILED = "SAVE_NOTES_FAILED";