export const FETCH_USER_STEP_DETAILS_REQUESTED = "FETCH_USER_STEP_DETAILS_REQUESTED";
export const FETCH_USER_STEP_DETAILS_SUCCEEDED = "FETCH_USER_STEP_DETAILS_SUCCEEDED";
export const FETCH_USER_STEP_DETAILS_FAILED = "FETCH_USER_STEP_DETAILS_FAILED";


export const FETCH_USER_CODE_REQUESTED = "FETCH_USER_CODE_REQUESTED";
export const FETCH_USER_CODE_SUCCEEDED = "FETCH_USER_CODE_SUCCEEDED";
export const FETCH_USER_CODE_FAILED = "FETCH_USER_CODE_FAILED";

export const SET_CURRENT_SHOW_CODE_TAB = "SET_CURRENT_SHOW_CODE_TAB";